server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

spring:
  thymeleaf:
    encoding: UTF-8
    content-type: text/html

hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
